### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/api/product/add
Content-Type: application/json

{
  "name": "Hardcover Lined Notebook",
  "description": "200 pages of premium-quality paper bound in a stylish hardcover, ideal for journaling or note-taking.",
  "price": 8.50,
  "category": "Stationery",
  "imageUrl": "https://example.com/images/products/notebook.jpg"
}

###
GET http://localhost:8080/api/product

###
DELETE http://localhost:8080/api/product/1

###
PUT http://localhost:8080/api/product/3
Content-Type: application/json

{
  "price": 100.0
}

###
POST http://localhost:8080/api/cart/add
Content-Type: application/json

{
  "userId": 1,
  "productId": 2,
  "quantity": 5
}
//{
//  "userId": 1,
//  "productId": 3,
//  "quantity": 2
//}


###update cart item quantity
PUT http://localhost:8080/api/cart/update
Content-Type: application/json

{
  "cartItemId": 1,
  "quantity": 8
}

### remove item from cart
DELETE http://localhost:8080/api/cart/remove/3

### get all user cart items
GET http://localhost:8080/api/cart/1

### place order using cart items
GET http://localhost:8080/api/order/make/1
###
GET http://localhost:8080/api/order/1

### purchase order
POST http://localhost:8080/api/order/purchase/1