### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST localhost:8084/api/user/register
Content-Type: application/json

{
  "name": "zozz",
  "email": "zozz@gmail.com",
  "password": "123salman",
  "role": "USER"
}


###
POST localhost:8084/api/user/login
Content-Type: application/json

{
  "email": "zozz@gmail.com",
  "password": "123salman"
}
